---
title: Besturing van een verkeerslichtsequentie met kras 1.4
hero_image: images / banner.png
description: Leer verkeerslicht-LED's beheren en codeer een reeks verkeerslichten met behulp van Scratch 1.4
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "fysiek computergebruik"
technologies: "elektronica, fysiek computergebruik, scratch"
site_areas: ""
steps:
  - 
    title: Invoering
  - 
    title: Wat je nodig zult hebben
  - 
    title: Verbind de LED's
  - 
    title: Bedien de LED's
  - 
    title: Volgorde verkeerslichten
