---
title: Steuern Sie eine Ampel Sequenz mit Scratch 1.4
hero_image: Bilder / Banner.png
description: Lernen Sie, wie Sie Ampel-LEDs steuern und eine Ampel-Sequenz mit Scratch 1.4 programmieren
theme: rot
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: Programmierung-0, Phys-Comp-0
interests: "physikalische Datenverarbeitung"
technologies: "Elektronik, Physical Computing, Scratch"
site_areas: ""
steps:
  - 
    title: Einführung
  - 
    title: Was wirst du brauchen
  - 
    title: Verbinde die LEDs
  - 
    title: Kontrolliere die LEDs
  - 
    title: Ampel Sequenz
