---
title: Traffic Lights with Scratch 1.4
hero_image: images / banner.png
description: トラフィックライトのLEDを制御し、Scratch 1.4を使用して信号灯のシーケンスをコードする方法を学ぶ
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: 前書き
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
