---
title: Traffic Lights with Scratch 1.4
hero_image: изображения / banner.png
description: Научете как да управлявате светодиодите със светофари и да кодирате последователността на светофара, като използвате Scratch 1.4
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Въведение
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
