---
title: Traffic Lights with Scratch 1.4
hero_image: images/banner.png
description: Lerne die Ampel-LEDs zu steuern und einen Ampelablauf mit Scratch 1.4 zu programmieren
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Einführung
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
