---
title: یک ترتیب چراغ های ترافیکی با ابتدا 1.4 را کنترل کنید
hero_image: images / banner.png
description: یاد بگیرید برای کنترل چراغ های چراغ راهنمایی و کد یک چراغ راهنمایی چراغ با استفاده از خراش 1.4
theme: سرخ
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0، phys-comp-0
interests: "محاسبات فیزیکی"
technologies: "الکترونیک، محاسبات فیزیکی، خراش"
site_areas: ""
steps:
  - 
    title: معرفی
  - 
    title: آنچه شما نیاز دارید
  - 
    title: LED ها را وصل کنید
  - 
    title: کنترل LED ها
  - 
    title: ترتیب چراغ راهنمایی
