---
title: Traffic Lights with Scratch 1.4
hero_image: images / banner.png
description: Tanuld meg, hogy irányítsd a közlekedési lámpa LED-eket, és kódolj egy közlekedési lámpa sorozatot a Scratch 1.4 segítségével
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Bevezetés
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
