---
title: Contrôle une Séquence de Feux de Circulation avec Scratch 1.4
hero_image: images/banner.png
description: Apprenez à contrôler les DELs du feu et à coder une séquence de feux de circulation avec Scratch 1.4
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Introduction
  - 
    title: Connecte les LED
  - 
    title: Contrôle les LED
  - 
    title: Séquence de feux de circulation
