---
title: Traffic Lights with Scratch 1.4
hero_image: images / banner.png
description: Apprenez à contrôler les voyants du feu et à coder une séquence de feux de circulation à l'aide de Scratch 1.4.
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: introduction
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
