---
title: Contrôler une séquence de feux de circulation avec Scratch 1.4
hero_image: images / banner.png
description: Apprenez à contrôler les voyants du feu et à coder une séquence de feux de circulation à l'aide de Scratch 1.4.
theme: rouge
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "informatique physique"
technologies: "électronique, informatique physique, scratch"
site_areas: ""
steps:
  - 
    title: introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: Connectez les LED
  - 
    title: Contrôler les LED
  - 
    title: Séquence de feux de circulation
