---
title: Traffic Lights with Scratch 1.4
hero_image: images/banner.png
description: Impara a controllare i semafori a LED e crea una sequenza di luci con Scratch 1.4
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Introduzione
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
